BLOCK_SITE: []
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  label: active
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: http://codey.cc/fcircle/
  theme: volantis
MAX_POSTS_NUM: 5
OUTDATE_CLEAN: 365
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: ''
  list:
  - - "\u8D30\u7339\u306E\u5C0F\u7A9D"
    - https://noionion.top/
    - https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg
  - - "Akilar\u306E\u7CD6\u679C\u5C4B"
    - https://akilar.top/
    - https://akilar.top/images/headimage.png
  - - elizen
    - https://elizen.me/
    - https://akilar.top/images/headimage.png
    - hello.xml
  - - "\u5F20\u6D2A"
    - https://blog.zhheo.com/
    - https://bu.dusays.com/2023/03/03/6401a7960c0fb.webp
  - - "\u675C\u8001\u5E08\u8BF4"
    - https://dusays.com/
    - https://cdn.dusays.com/avatar.png
  - - "\u5C0F\u5B59\u540C\u5B66"
    - https://blog.sunguoqi.com/
    - https://cdn.jsdelivr.net/gh/sun0225SUN/photos/images/202108300019556.gif
